version: '3'

services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=testpass
            - MYSQL_DATABASE=challenge
        volumes:
            - ./db/run:/var/lib/mysql
            - ./db/sql:/docker-entrypoint-initdb.d

    backend-golang:
        build: backend-golang
        links:
            - db
        ports:
            - "18000:8000"
    backend-java:
        build: backend-java
        links:
            - db
        ports:
            - "18000:8000"
    backend-node:
        build: backend-node
        links:
            - db
        ports:
            - "18000:8000"
    backend-python:
        build: backend-python
        links:
            - db
        ports:
            - "18000:8000"

    frontend-react:
        build: frontend-react
        links:
            - backend-python:backend
        ports:
            - "13000:3000"
